### ISSUE TITLE
Help :(

### ISSUE THREAD

**Issue by Elayan** [midoshouse/ootr-multiworld#44] opened 2024-06-20 20:26 UTC
error while trying to update Mido's House Multiworld from version 16.0.0:
feature not supported: 'stream reading entries with data descriptors (planned to be reintroduced)'
```rust
Zip(FeatureNotSupported("stream reading entries with data descriptors (planned to be reintroduced)"))
```

**Comment by fenhl** [comment] 2024-06-20 20:35
this is a bug in that version's updater. It has already been fixed in the current version, but due to the nature of updater bugs, you'll need to install the newest version from <https://midos.house/mw> as a workaround — no need to uninstall the old version or anything.

**Closed by fenhl** 2024-06-20 20:35 UTC

**Comment by fenhl** [comment] 2024-06-20 20:49
To give more details on this bug: The cause is the removal of a feature in a new version of the [`async_zip`](https://docs.rs/async_zip) crate, whose breaking changes [were undocumented at the time](https://github.com/Majored/rs-async-zip/issues/95). MH MW [version 16.0.1](https://github.com/midoshouse/ootr-multiworld/releases/tag/v16.0.1) included a version bump of `async_zip` which reintroduced that feature, but I wasn't aware of this bug at the time of the release, which is why the fix isn't mentioned in our changelog.

Ultimately, there should be tests catching bugs like this, so I've opened #45 for that.

**Comment by Elayan** [comment] 2024-06-20 21:13
Thank youuuu~~
